FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=production
ENV DRACHTIO_HOST=drachtio
ENV DRACHTIO_PORT=9022
ENV DRACHTIO_SECRET=cymru
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV LOGLEVEL=info
ENV LIVEKIT_URL=wss://21r9tnrcsmq.sip.livekit.cloud
ENV LIVEKIT_KEY=APIjlD4YtLc34Gl
ENV LIVEKIT_SECRET=eFiI3JxqZVVLb9wGGjYY6VfVRNP9BfuqEn7Y8sKd8hs
ENV BACKEND_URL=http://backend:3000
ENV PUBLIC_IP=100.25.218.14
ENV PUBLIC_SIP_PORT=5060

CMD ["npm", "start"]
